[package]
name = "abstracto3-macros"
description = "AbstractO3 Macros"
version = "0.1.0"
edition = "2021"

[lib]
name = "macros"
path = "lib.rs"

[dependencies]
syn = { version = "2", features = ["full"] }
proc-macro2 = "1.0"
quote = "1.0"
